RubyonRails/project/config/routes.rb
Rails.application.routes.draw do

    root :to => 'home#index'

    get 'upload', to: 'upload#index'
    post 'upload', to: 'upload#action'

    get 'authentication', to: 'authentication#index'
    post 'authentication', to: 'authentication#action'

    get 'pades_signature', to: 'pades_signature#index'
    post 'pades_signature', to: 'pades_signature#action'

    get 'pades_signature_without_integration', to: 'pades_signature_without_integration#index'
    post 'pades_signature_without_integration', to: 'pades_signature_without_integration#action'

    get 'cades_signature', to: 'cades_signature#index'
    post 'cades_signature', to: 'cades_signature#action'

    get 'full_xml_signature', to: 'full_xml_signature#index'
    post 'full_xml_signature', to: 'full_xml_signature#action'

    get 'xml_element_signature', to: 'xml_element_signature#index'
    post 'xml_element_signature', to: 'xml_element_signature#action'

    get 'batch_signature', to: 'batch_signature#index'
    post 'batch_signature/start/:id', to: 'batch_signature#start'
    post 'batch_signature/complete/:id', to: 'batch_signature#complete'

    get 'cades_batch_signature', to: 'cades_batch_signature#index'
    post 'cades_batch_signature/start/:id', to: 'cades_batch_signature#start'
    post 'cades_batch_signature/complete/:id', to: 'cades_batch_signature#complete'

end

RubyonRails/project/app/views/layouts/_error.html.erb
<div class="container">

  <h2>An error occurred:</h2>
  <h3 style="color: darkred"><%= @error %></h3>

</div>

RubyonRails/project/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">REST PKI Samples</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Authentication', authentication_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false">PAdES signature <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'With file already on server', pades_signature_path %></li>
            <li><%= link_to 'With file uploaded by user', upload_path(rc: 'pades_signature') %></li>
            <li><%= link_to 'Without integration between Web PKI and REST PKI', pades_signature_without_integration_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false">CAdES signature <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'With file already on server', cades_signature_path %></li>
            <li><%= link_to 'With file uploaded by user', upload_path(rc: 'cades_signature') %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">XML signature <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Full XML signature (enveloped signature)', full_xml_signature_path %></li>
            <li><%= link_to 'XML element signature', xml_element_signature_path %></li>
          </ul>
        </li>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Batch signature <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Simple PAdES batch signature', batch_signature_path %></li>
            <li><%= link_to 'Simple CAdES batch signature', cades_batch_signature_path %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

RubyonRails/project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>REST PKI Samples</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/menu' %>

<%= yield %>


</body>
</html>